# DESC: Last commit of the llamafile 0.8.13
- version: 0.8.13
  link: https://github.com/Mozilla-Ocho/llamafile/archive/b17ccd1ebaf534b63ee1dcb727dd2af479502339.zip
  folder_name: llamafile-b17ccd1ebaf534b63ee1dcb727dd2af479502339
